export const ERROR_CODES = {
	INTERNAL: "INTERNAL",
	VALIDATION_ERROR: "VALIDATION_ERROR",
	INFRASTRUCTURE_NOT_READY: "INFRASTRUCTURE_NOT_READY",
	DATABASE_UNAVAILABLE: "DATABASE_UNAVAILABLE",
	USGS_UNAVAILABLE: "USGS_UNAVAILABLE",
	USGS_PARSE_ERROR: "USGS_PARSE_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
